name: Export draw.io

on:
  push:
    paths:
      - '**/*.drawio'

jobs:
  export:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: rlespinasse/drawio-export-action@v2
        with:
          format: pdf
          path: figures
          output: exported
          transparent: false

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-export draw.io figures"
          file_pattern: exported/*
